import request from '../utils/request'

export const fetchDashboard = () => request.get('/admin/stats/overview')
export const fetchUsers = () => request.get('/admin/users')
export const deleteUser = (id) => request.delete(`/admin/users/${id}`)
export const updateUserEnabled = (id, enabled) => request.patch(`/admin/users/${id}/enabled`, { enabled })
export const fetchAdminSchools = () => request.get('/admin/schools')
export const createAdminSchool = (data) => request.post('/admin/schools', data)
export const deleteAdminSchool = (id) => request.delete(`/admin/schools/${id}`)
export const fetchAdminMajors = () => request.get('/admin/majors')
export const createAdminMajor = (data) => request.post('/admin/majors', data)
export const deleteAdminMajor = (id) => request.delete(`/admin/majors/${id}`)
export const fetchGuides = (params) => request.get('/admin/admissions', { params })
export const createGuide = (data) => request.post('/admin/admissions', data)
export const updateGuide = (id, data) => request.patch(`/admin/admissions/${id}`, data)
export const deleteGuide = (id) => request.delete(`/admin/admissions/${id}`)
export const fetchRatios = (params) => request.get('/admin/ratios', { params })
export const createRatio = (data) => request.post('/admin/ratios', data)
export const updateRatio = (id, data) => request.patch(`/admin/ratios/${id}`, data)
export const deleteRatio = (id) => request.delete(`/admin/ratios/${id}`)
export const fetchPolicyNews = (params) => request.get('/admin/policies', { params })
export const createPolicyNews = (data) => request.post('/admin/policies', data)
export const updatePolicyNews = (id, data) => request.patch(`/admin/policies/${id}`, data)
export const deletePolicyNews = (id) => request.delete(`/admin/policies/${id}`)
export const fetchAdminPosts = () => request.get('/admin/posts')
export const fetchAdminPostComments = (id) => request.get(`/admin/posts/${id}/comments`)
export const deleteAdminPost = (id) => request.delete(`/admin/posts/${id}`)
export const deleteAdminComment = (id) => request.delete(`/admin/posts/comments/${id}`)
export const fetchNotices = () => request.get('/notices')
export const createNotice = (data) => request.post('/admin/notices', data)
export const updateNotice = (id, data) => request.patch(`/admin/notices/${id}`, data)
export const deleteNotice = (id) => request.delete(`/admin/notices/${id}`)
export const fetchMaterialReviews = () => request.get('/admin/materials/reviews/pending')
export const fetchAdminMaterials = () => request.get('/admin/materials')
export const reviewMaterial = (id, reviewStatus, reviewComment = '') => request.patch(`/admin/materials/${id}/review`, { reviewStatus, reviewComment })
export const deleteMaterial = (id) => request.delete(`/admin/materials/${id}`)
export const fetchSystemConfigs = () => request.get('/admin/configs')
export const updateSystemConfig = (key, data) => request.patch(`/admin/configs/${key}`, data)
export const deleteSystemConfig = (key) => request.delete(`/admin/configs/${key}`)
export const fetchOperationLogs = () => request.get('/admin/logs')
export const fetchPapers = () => request.get('/admin/papers')
export const createPaper = (data) => request.post('/admin/papers', data)
export const deletePaper = (id) => request.delete(`/admin/papers/${id}`)
export const fetchQuestions = (paperId) => request.get('/admin/questions', {
  params: paperId ? { paperId } : {}
})
export const createQuestion = (data) => request.post('/admin/questions', data)
export const deleteQuestion = (id) => request.delete(`/admin/questions/${id}`)
export const fetchQuestionOptions = (id) => request.get(`/admin/questions/${id}/options`)
export const createQuestionOption = (id, data) => request.post(`/admin/questions/${id}/options`, data)
export const deleteQuestionOption = (id, optionId) => request.delete(`/admin/questions/${id}/options/${optionId}`)
